#!/usr/bin/env bash

# ------------------------------
# Yabai config

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# When an app is opened, it follows it (even through spaces), probably not needed if you "SIP your mac"
yabai -m signal --add event=window_created action="sh ~/.config/yabai/utils/focus_new_window.sh"

# ------------------------------
# Mouse settings

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

# ------------------------------
# Spaces setup

# TODO: condition instead of manual comment
# source ~/.config/yabai/utils/mono_screen.sh
source ~/.config/yabai/utils/dual_screens.sh

# ------------------------------
# Disable specific apps, they'll become free from tiling

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Réglages Système$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^licecap$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off

# ------------------------------
# Launch borders, for borders around windows

borders &

# ------------------------------
# Notify when theme switch

dark-notify -c 'source ~/.config/theme-notify/notify.sh' &
