#!/bin/bash

source ~/.config/theme-notify/variables.sh

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
source "$CONFIG_DIR/appearance.sh"

##### Changing Defaults #####
source "$CONFIG_DIR/defaults.sh"

##### Left Side #####
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

##### Right Side #####
# source "$ITEM_DIR/right.sh"
source "$ITEM_DIR/calendar.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
