import = [
    "~/.config/alacritty/themes/dark.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal = { family = "Cascadia Code" }

[window]
decorations = "buttonless"